name: Build flake

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Check flake
        run: nix flake check .#

      - name: Build flake
        run: nix build .#nixosConfigurations.zotac.config.system.build.toplevel
  home-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Build flake
        run: nix build .#homeConfigurations.dawidd6.activationPackage
