name: Build flake

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - flake.lock

concurrency:
  group: build-flake-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v8
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: ${{ github.repository_owner }}
          authToken: ${{ secrets.CACHIX_TOKEN }}

      - name: Build flake
        run: nix flake check
