name: Build flake

on:
  workflow_dispatch:
  push:

jobs:
  build-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Check flake
        run: nix flake check .#

      - name: Build NixOS
        run: nix build .#nixosConfigurations.zotac.config.system.build.toplevel

      - name: Build home-manager
        run: nix run .#homeConfigurations.dawidd6.activationPackage
