name: Build flake

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Format flake
        run: nix fmt

      - name: Repository status
        uses: numtide/clean-git-action@v1

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Check flake
        run: nix flake check

      - name: Repository status
        uses: numtide/clean-git-action@v1

  build-nixos:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Build flake
        run: |
          nix build .#nixosConfigurations.zotac.config.system.build.toplevel
          nix build .#nixosConfigurations.t440s.config.system.build.toplevel

      - name: Repository status
        uses: numtide/clean-git-action@v1

  build-home-manager:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Build flake
        run: |
          nix build .#homeConfigurations.dawid.activationPackage
          nix build .#homeConfigurations.dawidd6.activationPackage

      - name: Repository status
        uses: numtide/clean-git-action@v1
