name: Cache flake

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: cache-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: ${{ github.repository_owner }}
          authToken: ${{ secrets.CACHIX_TOKEN }}

      - name: Check flake
        run: nix flake check
