name: Check flake

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Check flake
        run: nix flake check

      - name: Repository status
        uses: CatChen/check-git-status-action@v1
