name: Test flake

on:
  workflow_dispatch:
  push:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Format flake
        run: nix fmt

      - name: Repository status
        uses: CatChen/check-git-status-action@v1
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - name: Cache store
        uses: DeterminateSystems/magic-nix-cache-action@v1

      - name: Check flake
        run: nix flake check

      - name: Repository status
        uses: CatChen/check-git-status-action@v1
