name: Update flake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

concurrency:
  group: update-flake-${{ github.ref }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Update flake
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          token: ${{ secrets.TOKEN }}
