name: Update flake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

concurrency:
  group: update-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2

      - run: nix flake show --json | jq > flake.json

      - run: nix build .#checks.dawid -o /tmp/dawid-current

      - run: nix flake update

      - run: nix build .#checks.dawid -o /tmp/dawid-proposed

      - run: nix store diff-closures /tmp/dawid-current /tmp/dawid-proposed
